# Generated by Django 4.0.5 on 2022-06-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_post_likes_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='image',
            new_name='post',
        ),
    ]
